# Algorithm specific parameters for SAC
# Can be merged with a main environment config

training:
  device: "cuda"
  seed: 42
  nb_envs: 6
  timesteps: 5000000
  save_freq: 50000
  log_dir: "log"
  log_freq: 1000
  resume_path: "log/AUVTracking_v1/LQR/CustomSACPolicy/12-17_21/rl_model_799968_steps.zip"

policy:
  net_arch:
    pi: [512, 256, 256]
    qf: [512, 256]
  
  features_extractor:
    type: "auv_track_launcher.networks.feature_network.Encoder"
    kwargs:
      features_dim: 512
      resnet_output_dim: 256

policy_hparams:
  policy: "CustomSACPolicy"
  policy_path: "auv_track_launcher.policys.custom_sac_policy.CustomSACPolicy"
  lr: 0.0001
  buffer_size: 100000
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  noise_std: 0.12
  start_timesteps: 1000
  
  # SAC specific
  auto_alpha: true
  alpha: 0.2
  alpha_lr: 0.0003

  replay_buffer:
    type: "ReplayBuffer"  # Options: "ReplayBuffer", "HerReplayBuffer"
    # her_kwargs:
    #   n_sampled_goal: 4
    #   goal_selection_strategy: "future"

  # Collect settings
  step_per_collect: 5
  update_per_step: 0.2
  n_step: 2
